name       : bbswitch
version    : 0.8
release    : 56
source     :
    - https://github.com/Bumblebee-Project/bbswitch/archive/v0.8.tar.gz : 76cabd3f734fb4fe6ebfe3ec9814138d0d6f47d47238521ecbd6a986b60d1477
license    : GPL-2.0
component  : kernel.image
summary    : Optimus hybrid GPU switching support
description: |
    bbswitch is a kernel module which automatically detects the required ACPI calls for two kinds of Optimus laptops.
builddeps  :
    - linux-lts
    - linux-lts-headers
permanent  :
    - /lib/modules
build      : |
    %make KVERSION="%kernel_version_lts%"
install    : |
    KVERSION="%kernel_version_lts%"
    install -D -m 00755 bbswitch.ko $installdir/lib/modules/${KVERSION}/misc/bbswitch.ko
